<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NpcInitiation</RootNamespace>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NpcMemory\NpcMemory.csproj" />
    <ProjectReference Include="..\NpcDecision\NpcDecision.csproj" />
  </ItemGroup>

</Project>
