using System.Text.Json;

namespace NpcTemperament;

/// <summary>
/// The seed table as data: <c>{ "characters": { "Abigail": { "warmth": 0.55, ... } } }</c>.
/// Hand edits go in a separate overrides file with the same shape (any subset of traits), applied
/// after generation, so regenerating never loses them.
/// </summary>
public sealed class TemperamentTable
{
    private readonly SortedDictionary<string, Temperament> _rows;

    public TemperamentTable(IDictionary<string, Temperament> rows)
        => _rows = new SortedDictionary<string, Temperament>(rows, StringComparer.Ordinal);

    public IReadOnlyDictionary<string, Temperament> Rows => _rows;

    /// <summary>A character's seed, or <see cref="Temperament.Neutral"/> for one not in the table.</summary>
    public Temperament Of(string npc) => _rows.TryGetValue(npc, out var t) ? t : Temperament.Neutral;

    /// <summary>Applies overrides (character -> trait -> value). Unknown traits throw; values are clamped to 0..1.</summary>
    public TemperamentTable WithOverrides(IReadOnlyDictionary<string, Dictionary<string, double>> overrides)
    {
        var rows = new Dictionary<string, Temperament>(_rows);
        foreach (var (npc, traits) in overrides.OrderBy(o => o.Key, StringComparer.Ordinal))
        {
            Temperament t = rows.TryGetValue(npc, out var existing) ? existing : Temperament.Neutral;
            foreach (var (trait, value) in traits.OrderBy(o => o.Key, StringComparer.Ordinal))
                t = t.With(trait, Math.Clamp(value, 0, 1));
            rows[npc] = t;
        }
        return new TemperamentTable(rows);
    }

    public string ToJson()
    {
        var doc = new SortedDictionary<string, object>(StringComparer.Ordinal)
        {
            ["note"] = "Seed temperaments, generated by tools/TemperamentExtractor from the game's dialogue and Data/Characters. "
                + "Put hand edits in temperament-overrides.json. See docs/spec/temperament.md.",
            ["characters"] = _rows.ToDictionary(r => r.Key, r => Temperament.TraitNames.ToDictionary(n => n, n => r.Value.Get(n))),
        };
        return JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true }) + "\n";
    }

    public static TemperamentTable FromJson(string json)
    {
        using var doc = JsonDocument.Parse(json);
        var rows = new Dictionary<string, Temperament>();
        foreach (var npc in doc.RootElement.GetProperty("characters").EnumerateObject())
        {
            Temperament t = Temperament.Neutral;
            foreach (var trait in npc.Value.EnumerateObject())
                t = t.With(trait.Name, trait.Value.GetDouble());
            rows[npc.Name] = t;
        }
        return new TemperamentTable(rows);
    }

    /// <summary>Reads an overrides file: character -> { trait: value }. Non-object entries (a "note") are ignored.</summary>
    public static Dictionary<string, Dictionary<string, double>> OverridesFromJson(string json)
    {
        using var doc = JsonDocument.Parse(json);
        var result = new Dictionary<string, Dictionary<string, double>>();
        foreach (var npc in doc.RootElement.EnumerateObject())
        {
            if (npc.Value.ValueKind != JsonValueKind.Object)
                continue;
            result[npc.Name] = npc.Value.EnumerateObject().ToDictionary(t => t.Name, t => t.Value.GetDouble());
        }
        return result;
    }
}
