<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NpcLive</RootNamespace>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NpcMotives\NpcMotives.csproj" />
    <ProjectReference Include="..\NpcIntents\NpcIntents.csproj" />
  </ItemGroup>

</Project>
